<?php

return [
    'audio' => [
        'ogg'   => base64_encode("OggS"),
        'opus'  => base64_encode("OggS"),
        'mp3'   => base64_encode("ID3"),
        'mp2'   => base64_encode("\xFF\xF3"),
        'wav'   => base64_encode("RIFF"),
        'aiff'  => base64_encode("FORM"),
        'aac'   => base64_encode("ftypM4A"),
        'm4a'   => base64_encode("ftypM4A"),
        'alac'  => base64_encode("ftypM4A"),
        'flac'  => base64_encode("fLaC"),
        'ac3'   => base64_encode("\x0B\x77"),
        'dts'   => base64_encode("\x7F\xFE\x80\x01"),
        'mid'   => base64_encode("MThd"),
        'amr'   => base64_encode("#!AMR"),
        'wma'   => base64_encode("\x30\x26\xB2\x75"),
        'ra'    => base64_encode(".ra"),
        'voc'   => base64_encode("Creative Voice File\x1A"),
        'vox'   => base64_encode("\x4C\x69\x6E\x20"),
        'snd'   => base64_encode(".snd"),
        'au'    => base64_encode(".snd"),
        's3m'   => base64_encode("SCRM"),
        'stm'   => base64_encode("!Scream!"),
        'mod'   => base64_encode("M.K."),
        'mo3'   => base64_encode("MO3"),
        'sf2'   => base64_encode("RIFF"),
        'it'    => base64_encode("IMPM"),
        'msv'   => base64_encode("\x4D\x53\x5F\x56"),
        'shn'   => base64_encode("ajkg"),
    ],

    'video' => [
        'mp4'   => base64_encode("\x00\x00\x00\x18ftypmp42"),
        'm4v'   => base64_encode("\x00\x00\x00\x18ftypM4V "),
        'mov'   => base64_encode("\x00\x00\x00\x18ftypqt  "),
        '3gp'   => base64_encode("\x00\x00\x00\x18ftyp3gp"),
        '3g2'   => base64_encode("\x00\x00\x00\x18ftyp3g2"),
        'webm'  => base64_encode("RIFF"),
        'avi'   => base64_encode("RIFF"),
        'flv'   => base64_encode("FLV"),
        'f4v'   => base64_encode("FLV"),
        'mkv'   => base64_encode("\x1A\x45\xDF\xA3"),
        'ts'    => base64_encode("\x47"),
        'wmv'   => base64_encode("\x30\x26\xB2\x75"),
        'rm'    => base64_encode(".RMF"),
        'divx'  => base64_encode("\x00\x00\x01\xBA"),
        'mpg'   => base64_encode("\x00\x00\x01\xBA"),
        'mpeg'  => base64_encode("\x00\x00\x01\xBA"),
        'asf'   => base64_encode("\x30\x26\xB2\x75"),
        'nut'   => base64_encode("nut\x00"),
        'viv'   => base64_encode("viv"),
        'roq'   => base64_encode("RoQ\x00"),
        'smk'   => base64_encode("SMK2"),
        'bik'   => base64_encode("BINK"),
        'mve'   => base64_encode("Interplay MVE"),
        'nsv'   => base64_encode("NSVf"),
        'r3d'   => base64_encode("RRED"),
        'mjpeg' => base64_encode("\xFF\xD8\xFF"),
    ],

    'image' => [
        'png'   => base64_encode("\x89PNG"),
        'jpg'   => base64_encode("\xFF\xD8\xFF"),
        'jpeg'  => base64_encode("\xFF\xD8\xFF"),
        'bmp'   => base64_encode("BM"),
        'tiff'  => base64_encode("II*\x00"),
        'ico'   => base64_encode("\x00\x00\x01\x00"),
        'webp'  => base64_encode("RIFF"),
        'heic'  => base64_encode("\x00\x00\x00\x18ftypheic"),
        'jfif'  => base64_encode("\xFF\xD8\xFF"),
        'exif'  => base64_encode("\xFF\xD8\xFF"),
    ],

    'document' => [
        'pdf'   => base64_encode("%PDF"),
        'doc'   => base64_encode("\xD0\xCF\x11\xE0"),
        'docx'  => base64_encode("PK\x03\x04"),
        'ppt'   => base64_encode("\xD0\xCF\x11\xE0"),
        'pptx'  => base64_encode("PK\x03\x04"),
        'xls'   => base64_encode("\xD0\xCF\x11\xE0"),
        'xlsx'  => base64_encode("PK\x03\x04"),
        'rtf'   => base64_encode("{\\rtf"),
        'odt'   => base64_encode("PK\x03\x04"),
        'odp'   => base64_encode("PK\x03\x04"),
        'ods'   => base64_encode("PK\x03\x04"),
        'epub'  => base64_encode("PK\x03\x04"),
        'xps'   => base64_encode("\x09\x08\x10\x00"),
    ],
];
